#!/bin/bash
set -x

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
    GIT_TREE_STATE="active"
else
    VERSION="${COMMIT}${DIRTY}"
    GIT_TREE_STATE="dirty"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

HELM_TAG_DEV=dev
HELM_VERSION_DEV=0.0.0-dev
HELM_TAG=${TAG:-${VERSION}}
HELM_VERSION=${HELM_TAG/v/}

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
    HELM_TAG=$HELM_TAG_DEV
    HELM_VERSION=$HELM_VERSION_DEV
fi

BIN_NAME="test-extension-operator"
BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
